config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'

  resources :artists, :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # GET /artists
  def index
    @artists = Artist.all
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # POST /artists
  def create
    @artist = Artist.create!(artist_params)

    redirect_to artist_path(@artist)
  end

  # GET /artists/:id
  def show
    @artist = Artist.find(params[:id])
  end

  # GET /artists/:id/edit
  def edit
    @artist = Artist.find(params[:id])
  end


  # PUT /artists/:id
  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)

    redirect_to artist_path(@artist)
  end

  # DELETE /artists/:id
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  def index
    @songs = Song.all
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # POST /songs
  def create
    @song = Song.create(song_params)

    redirect_to songs_path(@song)
  end

  # GET /songs/:id
  def show
    @song = Song.find(params[:id])
  end

  # GET /songs/:id/edit
  def edit
    @song = Song.find(params[:id])
  end

  # PUT /songs/:id
  def update
    @song = Song.find(params[:id])
    @song.update(song_params)

    redirect_to songs_path(@song)
  end

  # DELETE /songs/:id
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :album, :preview_url, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.submit %>
<% end %>

<%= form_for @artist, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/artists/index.html.erb
<h2>Artists <%= link_to "(+)", new_artist_path %></h2>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, artist %>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h2>New Artist</h2>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h2><%= @artist.name %> <%= link_to "(edit)", edit_artist_path(@artist) %></h2>
<h4><%= @artist.nationality %></h4>

<%= image_tag @artist.photo_url, class: "artist-photo" %>

<h3>Songs <%= link_to "(+)", new_song_path %></h3>

<ul>
  <% @artist.songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} (#{song.album})", song %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControllersLesson</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :preview_url %>
  <%= f.text_field :preview_url %>

  <%= f.label :artist_id %>
  <%= f.text_field :artist_id %>

  <%= f.submit %>
<% end %>

<%= form_for @song, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/songs/index.html.erb
<h2>Songs <%= link_to "(+)", new_song_path %></h2>

<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} - #{song.artist.name}", song %>
    </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h2>New Song</h2>

<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :preview_url %>
  <%= f.text_field :preview_url %>

  <%= f.label :artist_id %>
  <%= f.text_field :artist_id %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h2><%= @song.title %> <%= link_to "(edit)", edit_song_path(@song) %></h2>
<h3>By: <%= @song.artist.name %></h3>

Album: <%= @song.album %></br>

<audio controls src="<%= @song.preview_url %>"></audio>